name: tp
channels:
    - defaults
    - conda-forge
    - simpleitk
dependencies:
    - python=3.9
    # UI
    - pyside2>=5.13
    # data analysis
    - numpy
    - nomkl
    - matplotlib-base
    - seaborn-base
    - pandas
    - openpyxl
    # image
    - opencv
    - scikit-image
    - tensorflow
    - simpleitk
    # dev
    - loguru
    - rich
    - omegaconf
    - pdoc3
    - click
    - pytest
    - pylint
    - yapf
    - mypy
    - cx_freeze
