name: tp
channels:
    - defaults
    - conda-forge
    - simpleitk
dependencies:
    - python=3.9
    # UI
    - pip
    - pip:
        - PySide2>=5.15 # or
        - PyQt5>=5.15
        - matplotlib-backend-qtquick
    # data analysis
    - numpy
    - nomkl
    - matplotlib-base
    - seaborn-base
    - pandas
    - openpyxl
    # image
    - opencv
    - scikit-image
    - tensorflow
    - simpleitk
    # misc
    - loguru
    - rich
    - click
    - omegaconf
    - cx_freeze
    - pdoc3
    # dev
    - pytest
    - pylint
    - yapf
    - mypy
