name: tp
channels:
  - conda-forge
  - simpleitk
dependencies:
  - python>=3.11
  # UI
  - pip
  - pip:
      - webp
      - PyQt5>=5.15
      - PyQtWebEngine
  # data analysis
  - numpy
  - nomkl
  - scikit-learn
  - matplotlib-base=3.7
  - seaborn-base
  - pandas
  - openpyxl
  # image
  - opencv
  - scikit-image
  - onnxruntime
  - simpleitk
  # misc
  - loguru
  - rich
  - click
  - omegaconf
  - cx_freeze
  - pywin32
  - toolz
  # dev
  - pytest
  - pyink
  - pylint
  - mypy
  - ruff
