name: tp
channels:
    - defaults
    - conda-forge
    - simpleitk
dependencies:
    - python>=3.9
    # UI
    - pip
    - pip:
          - webp
          - PyQt5>=5.15 # or
          # - PySide2>=5.15
          # - matplotlib-backend-qtquick
    # data analysis
    - numpy
    - nomkl
    - matplotlib-base
    - seaborn-base
    - pandas
    - openpyxl
    # image
    - opencv
    - scikit-image
    - onnxruntime
    - simpleitk
    # misc
    - loguru
    - rich
    - click
    - omegaconf
    - cx_freeze
    - pywin32
    # dev
    - pytest
    - pylint
    - yapf
    - toml
    - mypy
