name: tp
channels:
    - defaults
    - conda-forge
    - simpleitk
dependencies:
    - python
    - pip
    # UI
    - pip:
          - PySide2>=5.15
          - PyQt5>=5.15
    # data analysis
    - numpy
    - nomkl
    - matplotlib
    - seaborn
    - pandas
    - openpyxl
    # image
    - opencv
    - scikit-image
    - tensorflow
    - simpleitk
    # dev
    - loguru
    - rich
    - omegaconf
    - pdoc3
    - click
    - pytest
    - pylint
    - yapf
    - mypy
    - cx_freeze
