[tool.yapf]
based_on_style = 'google'
indent_width = 2

[tool.yapfignore]
ignore_patterns = ['build/']

[tool.isort]
profile = 'google'

[tool.ruff]
select = ['ALL']
ignore = [
    'ANN',
    'COM',
    'D100',
    'D101',
    'D102',
    'D103',
    'D104',
    'D105',
    'D106',
    'D107',
    'D400',
    'I',
    'PTH123',
    'Q',
    'S101',
    'TCH',
    'TRY',
]
exclude = ['mbq', 'script']
per-file-ignores = { '__init__.py' = ['F401'] }
cache-dir = '.cache/ruff'

[tool.ruff.pydocstyle]
convention = 'numpy'

[tool.ruff.pylint]
max-args = 7

[tool.pylint.messages_control]
enable = [
    'F',
    'E',
    'anomalous-backslash-in-string',
    'bad-format-string',
    'bad-open-mode',
    'binary-op-exception',
    'duplicate-key',
    'global-variable-not-assigned',
    'unnecessary-semicolon',
    'unreachable',
]
disable = [
    'bad-indentation',
    'c-extension-no-member',
    'fixme',
    'import-error',
    'invalid-name',
    'missing-class-docstring',
    'missing-function-docstring',
    'missing-module-docstring',
    'redefined-outer-name',
    'too-few-public-methods',
    'too-many-arguments',
    'trailing-whitespace',
    'unused-argument',
    'unused-import',
    'unused-variable',
    'wrong-import-order',
]

[tool.mypy]
disable_error_code = ['var-annotated', 'import']
check_untyped_defs = true
warn_unused_ignores = true
warn_unused_configs = true
exclude = ['.*/mbq/.*']
cache_dir = '.cache/mypy'

[tool.pytest.ini_options]
addopts = '-v'
cache_dir = '.cache/pytest'
