[tool.ruff]
target-version = 'py311'
preview = true
output-format = 'concise'
indent-width = 2
respect-gitignore = false
exclude = ['mbq', 'script', 'pano/registration/evaluation/_*']

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.ruff.lint]
select = ['ALL']
ignore = [
    'ANN',    # flake8-annotations
    'COM',    # flake8-commas
    'CPY',    # flake8-copyright
    'D1',     # pydocstyle: D1*
    'D4',     # pydocstyle: D4*
    'E1',     # pycodestyle: E1*
    'E2',     # pycodestyle: E2*
    'FIX',    # flake8-fixme
    'INP',    # flake8-no-pep420
    'ISC001', # flake8-implicit-str-concat: single-line-implicit-string-concatenation
    'PTH123', # flake8-use-pathlib: builtin-open
    'Q',      # flake8-quotes
    'S',      # flake8-bandit
    'T20',    # flake8-print
    'TD',     # flake8-todos
]
extend-safe-fixes = [
    'EM',  # flake8-errmsg
    'TCH', # flake8-type-checking
    'TRY', # tryceratops
]
per-file-ignores = { '__init__.py' = ['F401'] }

[tool.ruff.lint.pydocstyle]
convention = 'numpy'

[tool.ruff.lint.pylint]
max-args = 7

[tool.pylint.messages_control]
confidence = ['HIGH', 'INFERENCE', 'INFERENCE_FAILURE']
disable = ['C', 'R', 'I', 'fixme']

[tool.mypy]
disable_error_code = ['var-annotated', 'import']
check_untyped_defs = true
warn_unused_ignores = true
warn_unused_configs = true
exclude = ['.*/mbq/.*']

[tool.pytest.ini_options]
addopts = '-v'

[tool.typos.default.extend-words]
ANLY = 'ANLY'
