[tool.ruff]
target-version = 'py311'
preview = true
select = ['ALL']
ignore = [
    'ANN',
    'COM',
    'CPY',
    'D1',
    'D4',
    'E1',
    'E2',
    'EM101',
    'FIX',
    'INP',
    'ISC001',
    'PTH123',
    'Q',
    'S101',
    'T20',
    'TD',
    'TRY003',
]
exclude = ['mbq', 'script', 'pano/registration/evaluation/_*']
per-file-ignores = { '__init__.py' = ['F401'] }
indent-width = 2
cache-dir = '.cache/ruff'

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.ruff.pydocstyle]
convention = 'numpy'

[tool.ruff.pylint]
max-args = 7

[tool.mypy]
disable_error_code = ['var-annotated', 'import']
check_untyped_defs = true
warn_unused_ignores = true
warn_unused_configs = true
exclude = ['.*/mbq/.*']
cache_dir = '.cache/mypy'

[tool.pytest.ini_options]
addopts = '-v'
cache_dir = '.cache/pytest'

[tool.typos.default.extend-words]
ANLY = 'ANLY'
