[tool.pyink]
pyink-use-majority-quotes = true
pyink-indentation = 2
preview = true

[tool.isort]
profile = 'black'

[tool.ruff]
target-version = 'py311'
select = ['ALL']
ignore = [
    'ANN',
    'COM',
    'D100',
    'D101',
    'D102',
    'D103',
    'D104',
    'D105',
    'D106',
    'D107',
    'D400',
    'EM101',
    'FIX',
    'I',
    'PTH123',
    'Q',
    'S101',
    'TCH',
    'TD',
    'TRY',
]
exclude = ['mbq', 'script']
per-file-ignores = { '__init__.py' = ['F401'] }
cache-dir = '.cache/ruff'

[tool.ruff.pydocstyle]
convention = 'numpy'

[tool.ruff.pylint]
max-args = 7

[tool.mypy]
disable_error_code = ['var-annotated', 'import']
check_untyped_defs = true
warn_unused_ignores = true
warn_unused_configs = true
exclude = ['.*/mbq/.*']
cache_dir = '.cache/mypy'

[tool.pytest.ini_options]
addopts = '-v'
cache_dir = '.cache/pytest'

[tool.typos.default.extend-words]
ANLY = 'ANLY'
