camera:
    default:
        IR_AOV: null # 열화상 시야각 [degree]
        VIS_AOV: null # 실화상 시야각 [degree]
        scale: 0.75 # IR / VIS image scale
        translation: null
    FLIR E95:
        IR_AOV: null
        VIS_AOV: null
        scale: 0.758
        translation: [-17.16, -8.2]
    FLIR T540:
        IR_AOV: null
        VIS_AOV: null
        scale: 0.735
        translation: [5.07, -12.6]
color:
    colormap: iron # optional, {"iron", "inferno", "rainbow", ...}
    extract_color_image: true
file:
    size_limit: 10000 # [pixel]
    FLIR:
        IR: "*.jpg"
    testo:
        IR: "*.xlsx"
        VIS: "*_실화상 이미지.JPG"
    force_horizontal: false # {false, "CW", "CCW"}
    save_mat: false
registration:
    metric: JointHistMI # {"JointHistMI", "MattesMI", "MeanSquare", ...}
    transformation: Similarity # {"Similarity", "Affine"}
    bins: auto # {int, "auto", "fd", "sqrt", ...}
    optimizer: gradient_descent # {"gradient_descent", "powell"}
    preprocess:
        equalize_histogram: true
        unsharp: false
        edge: false
panorama:
    separate: true
    target: IR # {"IR", "VIS"}
    stitch:
        perspective: panorama # {"panorama", "scan"}
        warp: plane # {"plane", "spherical", "affine", ...}
        compose_scale: 1.0
        work_scale: 1.0
        warp_threshold: 20.0
        crop: true
    blend:
        type:
            # {"feather", "multiband", "no"}
            IR: "feather"
            VIS: "no"
        strength:
            IR: 0.05
            VIS: 0.05
    preprocess:
        IR:
            masking_threshold: -30.0
            contrast: equalization # {"equalization", "normalization", null}
            denoise: bilateral # {"bilateral", "gaussian", null}
            bilateral_args: # optional
                d: -1
                sigmaColor: 20
                sigmaSpace: 10
            gaussian_args: # optional
                ksize: [5, 5]
                sigmaX: 5
        VIS:
            masking_threshold: null
            contrast: normalization # {"equalization", "normalization", null}
            denoise: gaussian # {"bilateral", "gaussian", null}
            bilateral_args: # optional
                d: -1
                sigmaColor: 20
                sigmaSpace: 10
            gaussian_args: # optional
                ksize: [5, 5]
                sigmaX: 5
distort_correction:
    apply_mask: true
    correction:
        threshold: 5 # [degree]
        ransac_iter: 2000
        clip_factor: 5
        vp_iter: 5
        erode: 50 # [iteration]
        strict: False
        margin: 0.1
    canny: # optional
        sigma: 3.0
        low_threshold: null
        high_threshold: null
        use_quantiles: false
    hough: # optional
        threshold: 10
        line_length: 10
        line_gap: 5
output:
    canny:
        sigma: 2.0
        low_threshold: null
        high_threshold: null
        use_quantiles: false
    hough:
        threshold: 10
        line_length: 50
        line_gap: 25
    edgelet:
        segmentation: true
        window_threshold: 0.5
        slab_position: 0.5
        max_count: 10
        distance_threshold: 10
        angle_threshold: 5
